[2025-04-26 16:19:46] [INFO] 启动程序
[2025-04-26 16:19:46] [ERROR] Uncaught exception
Traceback (most recent call last):
  File "d:\Folra程序\新东方N1\XDFBoom_Toolkit\Main\main.py", line 33, in <module>
    main()
  File "d:\Folra程序\新东方N1\XDFBoom_Toolkit\Main\main.py", line 27, in main
    window = FluentMainWindow()
             ^^^^^^^^^^^^^^^^^^
  File "d:\Folra程序\新东方N1\XDFBoom_Toolkit\Main\gui\FluentMainWindow_v2.py", line 27, in __init__
    self.nav_interface = NavigationInterface(self, showMenuButton=True)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\qfluentwidgets\components\navigation\navigation_interface.py", line 35, in __init__
    super().__init__(parent=parent)
TypeError: QWidget(parent: Optional[QWidget] = None, flags: Union[Qt.WindowFlags, Qt.WindowType] = Qt.WindowFlags()): argument 'parent' has unexpected type 'FluentMainWindow'
[2025-05-05 10:32:48] [ERROR] [logging_config.py:52] 未捕获的异常
Traceback (most recent call last):
  File "d:\Folra程序\新东方N1\XDFBoom_Toolkit\main.py", line 3, in <module>
    from gui.FluentMainWindow import FluentMainWindow
  File "d:\Folra程序\新东方N1\XDFBoom_Toolkit\gui\FluentMainWindow.py", line 13, in <module>
    from gui.pages.adb_page import ADBPage
  File "d:\Folra程序\新东方N1\XDFBoom_Toolkit\gui\pages\adb_page.py", line 2, in <module>
    from qfluentwidgets import (
ImportError: cannot import name 'TextBox' from 'qfluentwidgets' (C:\Program Files\Python311\Lib\site-packages\pyside6_fluent_widgets-1.7.7-py3.11.egg\qfluentwidgets\__init__.py)
[2025-05-05 10:33:35] [ERROR] [logging_config.py:52] 未捕获的异常
Traceback (most recent call last):
  File "d:\Folra程序\新东方N1\XDFBoom_Toolkit\main.py", line 3, in <module>
    from gui.FluentMainWindow import FluentMainWindow
  File "d:\Folra程序\新东方N1\XDFBoom_Toolkit\gui\FluentMainWindow.py", line 13, in <module>
    from gui.pages.adb_page import ADBPage
  File "d:\Folra程序\新东方N1\XDFBoom_Toolkit\gui\pages\adb_page.py", line 2, in <module>
    from qfluentwidgets import (
ImportError: cannot import name 'SimpleListWidget' from 'qfluentwidgets' (C:\Program Files\Python311\Lib\site-packages\pyside6_fluent_widgets-1.7.7-py3.11.egg\qfluentwidgets\__init__.py)
[2025-05-05 10:33:51] [ERROR] [logging_config.py:52] 未捕获的异常
Traceback (most recent call last):
  File "d:\Folra程序\新东方N1\XDFBoom_Toolkit\main.py", line 3, in <module>
    from gui.FluentMainWindow import FluentMainWindow
  File "d:\Folra程序\新东方N1\XDFBoom_Toolkit\gui\FluentMainWindow.py", line 13, in <module>
    from gui.pages.adb_page import ADBPage
  File "d:\Folra程序\新东方N1\XDFBoom_Toolkit\gui\pages\adb_page.py", line 7, in <module>
    from logic.adb_tool import run_adb_command
  File "d:\Folra程序\新东方N1\XDFBoom_Toolkit\logic\adb_tool.py", line 5, in <module>
    from core.path_manager import ADB_PATH
ImportError: cannot import name 'ADB_PATH' from 'core.path_manager' (d:\Folra程序\新东方N1\XDFBoom_Toolkit\core\path_manager.py)
[2025-06-15 16:01:26] [ERROR] [logging_config.py:52] 未捕获的异常
Traceback (most recent call last):
  File "d:\快速访问\DOCUMENT\GitHub\XDFBoom_Toolkit\main.py", line 3, in <module>
    from gui.FluentMainWindow import FluentMainWindow
  File "d:\快速访问\DOCUMENT\GitHub\XDFBoom_Toolkit\gui\FluentMainWindow.py", line 13, in <module>
    from gui.pages.adb_page import ADBPage
  File "d:\快速访问\DOCUMENT\GitHub\XDFBoom_Toolkit\gui\pages\adb_page.py", line 7, in <module>
    from logic.adb_tool import run_adb_command
  File "d:\快速访问\DOCUMENT\GitHub\XDFBoom_Toolkit\logic\adb_tool.py", line 5, in <module>
    from core.path_manager import ADB_PATH
ImportError: cannot import name 'ADB_PATH' from 'core.path_manager' (d:\快速访问\DOCUMENT\GitHub\XDFBoom_Toolkit\core\path_manager.py)
